GET http://www.baidu.com#fragment  HTTP/1.1

###
GET http://fanyi.baidu.com/translate/?query=#en/zh/rest#fragment HTTP/1.1

###
POST http://localhost:8080/post HTTP/1.1

Content-Type: application/json
{
    "name":"xiaoming",
    "time":"2021.10.10"
}
