JL:
	julia ./no_go_file/main.jl

GO:
	go run main.go

PY:
	python ./no_go_file/main.py

CPP:
	g++ ./no_go_file/main.cpp -o a.out
	./a.out

CC:
	gcc ./no_go_file/main.c -o main.o
	./main.o

clean:
	rm -rf ./no_go_file/*.o  ./no_go_file/*.out 